#!/bin/bash
# export-crypto.sh
# Export cryptographic credentials and connection profile from Fabric network

echo "Exporting Fabric Crypto Material and Connection Profile..."

# Define paths
FABRIC_DIR="../fabric-samples/test-network"
DEST_DIR="./config"
CRYPTO_DEST="./wallet"

# Create destination config directory
mkdir -p ${DEST_DIR}

# 1. Copy the Connection Profile (connection-org1.json)
CP_PATH="${FABRIC_DIR}/organizations/peerOrganizations/org1.example.com/connection-org1.json"
if [ -f "$CP_PATH" ]; then
    cp "$CP_PATH" "${DEST_DIR}/"
    echo "✅ Connection Profile exported to ${DEST_DIR}/connection-org1.json"
else
    echo "❌ Connection Profile not found at ${CP_PATH} (Is the network running?)"
    exit 1
fi

# Note: The wallets (crypto materials for admin/appUser) will be generated by enrollAdmin.js and registerUser.js
echo "🎉 Export complete."
echo "Please run 'npm install fabric-network fabric-ca-client' and then execute 'node src/enrollAdmin.js' followed by 'node src/registerUser.js'."
